Create header tagline
AnsarIbrahim/Portfolio-Mobile-Version pull request #2
Opened 2023-01-18 15:48 UTC by AnsarIbrahim

### This PR adds the following sections :
- header
- tagline

2023-01-18 16:35 UTC, Felix45 requested changes
Hi @AnsarIbrahim , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

## Highlights :heavy_check_mark: 
- [ ] No linter errors :heavy_check_mark: 
- [ ] Professional readme file :heavy_check_mark: 
- [ ] GitHub flow is correctly used :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 06:30 UTC, Ibizugbe requested changes
Hi @AnsarIbrahim 👋, 

![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d](https://user-images.githubusercontent.com/64643995/213370695-7cf24a64-f34a-4e48-9f0f-c4be117978ab.gif)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅
- liniters are passing✅
- github flow has been used✅


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- see comment below🤗
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 06:30 UTC, Ibizugbe commented on index.html
> +                </div>
I think the positioning of your tests when compared to the design looks a little bit different😉 also, you have done nice work implementing the changes suggested by the previous reviewer😉 but the font properties requested by the previous are still not implemented. take a look at the image below🤗
Figma
<img width="197" alt="figma__intro" src="https://user-images.githubusercontent.com/64643995/213370170-7a213a69-ab7a-4606-875f-db8476c7daac.png">

your app
<img width="275" alt="your__header" src="https://user-images.githubusercontent.com/64643995/213370240-f23864fa-95c0-4680-97a2-4cc63eeae700.png">

kindly mind the colors, the blue represents the background🤗 kindly add the changes.

2023-01-19 06:30 UTC, Ibizugbe commented on style.css
> +  font-family: 'Inter', sans-serif;
[OPTIONAL] I think there won't be any need to state the font-family property over again since you already specified a general rule for the font family at the beginning of the stylesheet😉 remember to always keep your code DRY😉 to minimize the lines of code in your project🤗

2023-01-19 07:28 UTC, binhussen approved these changes
Hi @AnsarIbrahim , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 07:28 UTC, binhussen commented on style.css
> +  padding-top: 40px;
- [Optional] Kindly, giving this padding is unnecessary to stick the header f the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988&t=uOjNwaXP1YrJtj1t-0) 👌👍

2023-01-19 07:28 UTC, binhussen commented on style.css
> +    height: 100px;
- [Optinal] Kindly this height make your hamburger lose the straightness of the logo, please remove it 👍👌

2023-01-19 07:28 UTC, binhussen commented on style.css
> +  color: #90ee90;
- [Optional] Kindly use the exact [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988&t=uOjNwaXP1YrJtj1t-0) color, to make your page looks better 👌👍`color: #36B37F;`

2023-01-19 07:35 UTC, merged